### ISSUE TITLE
[Feature] Place 모델 설계 & Place 관련 API 완성

### ISSUE THREAD

**Issue by dudtlstm** [SOOM-shinjin/SOOM-server#5]
## 📑 이슈 설명
Place 모델을 모두 설계합니다.
그후, Place와 관련된 API를 모두 개발합니다.

[API 종류]
- 플레이스의 모든 정보를 불러오는 API
아래 3개는 필터링 기능을 이용하여 개발하면 될 것으로 생각
- '가볼 만한 곳' API
- '음식점' API
- '숙소' API 

## ✔️ TO-DO
- [x] Place 모델 설계
- [x] 플레이스의 모든 정보를 불러오는 API 구축
- [x] 필터링 기능 적용 -> API 3개 뽑아내기
- [ ] 사진 추가하기
- [ ] 유저 기능 완료 후 좋아요 기능

## 💬 기타
아자아자파이팅!!!!
